name: "Deploy with main"
on:
  # Manual trigger
  #No changes made
  workflow_dispatch:
  push:
    paths:
      - 's3/**'
  pull_request:
    branches: [ main ]
    paths:
      - 's3/**'
defaults:
  run:
    shell: bash
    working-directory: s3
jobs:
  terraform:
    name:   ${{matrix.runner}} - ${{ matrix.environment }}
    runs-on: [ '${{ matrix.runner }}']
    strategy:
      max-parallel: 1
      matrix:
         include:
           - environment: test
             runner: ubuntu-latest
           - environment: prod
             runner: ubuntu-18.04
    env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-2
    steps:
      - uses: actions/checkout@v2
      - name: Copy files to the test website with the AWS CLI
        run: |
         aws s3 sync . s3://devops4solutions-target --region us-east-2
      - name: Run only if push to main branch
        # PERMITS VALIDATING BRANCHES/PULL REQUESTS WITHOUT CHANGING ANYTHING
        if: github.ref == 'refs/heads/main'
        id: apply
        run: echo "Run only when push to main branch"
