name: "Path Filter"
on:
  push:
    branches:
      - main
    paths:
      - 'folder-1/**'
      - 'folder-2/**'
jobs:
  changes:
    name: Detect Changes in folder
    runs-on: ubuntu-latest
    outputs:
      names: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
    - name: Detect Changes
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          folder-1:
            - 'folder-1/**'
          folder-2:
            - 'folder-2/**'
  deploy:
    needs: changes
    if: ${{ needs.changes.outputs.names != '[]' }}
    name:  ${{matrix.name}} - ${{ matrix.environment }}
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
         name: ${{ fromJSON(needs.changes.outputs.names) }}
         environment: [ test,prod]
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Checking the folder name
        run: |
         echo "Running for folder ${{ matrix.name }}"
